server:
  port: 8085

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    preferIpAddress: true

spring:
  application:
    name: book-service
  cloud:
    config:
      name: book-client-config
      fail-fast: true
  config:
    import: optional:configserver:http://localhost:8087/
#  profiles:
#    active: prod, default, dev
